update to use safecache types for controller
openstack-charmers/charm-test-infra pull request #19
Opened 2018-07-03 14:10 UTC by ChrisMacNaughton

2018-07-03 14:10 UTC, ChrisMacNaughton commented
The cores and memory constraints have to be removed because they conflict with the instance-type constraint

2018-07-03 14:11 UTC, gnuoy commented
LGTM

2019-10-03 13:42 UTC, ryan-beisner requested changes
-1 from me.

2019-10-03 13:42 UTC, ryan-beisner commented on juju-openstack-controller-example.sh
> +: ${BOOTSTRAP_CONSTRAINTS:="virt-type=kvm instance-type=m1.safecache.large"}
I'm concerned that this will fail if that very-specifically-named flavor doesn't exist.

2021-02-01 10:01 UTC, AurelienLourot commented
@ChrisMacNaughton do we still want this?

2021-02-01 10:12 UTC, ChrisMacNaughton commented
Nah, as we're not actually keeping controllers around anymore :)

2021-02-01 10:12 UTC, closed without merging