Check juju and openstack command exist
openstack-charmers/charm-test-infra pull request #39
Opened 2019-10-21 04:34 UTC by xiywang

If the commands are not exist, install before run the script.

Signed-off-by: Xiyue Wang <celia.wang@canonical.com>

2019-10-21 20:58 UTC, thedac requested changes
Celia,
Thanks for the PR!

I have a minor nit change request.

Since this script affects OSCI I am also going to ask for Ryan to review it for its functionality before landing.

2019-10-21 20:58 UTC, thedac commented on juju-openstack-controller-example.sh
> +if [ $? == 1 ]
Our convention is to do the if, test, and then all on the same line:
if [sometest]; then

2019-10-21 20:58 UTC, thedac commented on juju-openstack-controller-example.sh
> +then
Same

2020-03-05 10:07 UTC, ryan-beisner requested changes
Thank you for the proposal.  However, I do not want to introduce commands which require sudo into this script.  That will fail in our CI as the CI user does not have the ability to sudo.  The dependencies are expected to be installed in advance (by whatever means the user chooses), and maybe we should say that clearly somewhere.

2021-02-01 09:59 UTC, AurelienLourot commented
Closing for the reasons mentioned above, thanks!

2021-02-01 09:59 UTC, closed without merging